export const WITHDRAWAL_PREPARATION_TTL_SECONDS = 2 * 60;
export const WITHDRAWAL_SUBMISSION_BUFFER_SECONDS = 60;
export const WITHDRAWAL_TRANSACTION_TIMEOUT_SECONDS = (
  WITHDRAWAL_PREPARATION_TTL_SECONDS + WITHDRAWAL_SUBMISSION_BUFFER_SECONDS
);
export const WITHDRAWAL_PREPARATION_TTL_MS = WITHDRAWAL_PREPARATION_TTL_SECONDS * 1000;
